language: d

d:
  - dmd
  - gdc

script:
  # Compile & test with DMD
  - if [[ "${DC}" == "dmd" ]]; then  dub test --compiler=${DC};            fi
  # Compiler to static binary with gdc
  - if [[ "${DC}" == "gdc" ]]; then  dub build -c static --compiler=${DC}; fi
