sudo: required

language: d

services:
  - docker

d:
  - dmd
  - dmd-beta
  - dmd-nightly
  - ldc

matrix:
  include:
    - d: ldc-1.7.0
      env: TOUR_DEPLOY=1


cache:
  - $HOME/.dub

branches:
  only:
    - master
    - testing

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libevent-dev

script:
  # Update all language repos to their latest content
  - git pull --recurse-submodules
  - git submodule update --remote --recursive
  # Compile & test with all compilers
  # https://issues.dlang.org/show_bug.cgi?id=13742 + separate linking not implemented for LDC
  - if [[ "${DC}" == "dmd" ]]; then  dub test --compiler=${DC} --build=unittest-cov --build-mode=singleFile ; else dub test --compiler=${DC} ; fi
  # Temporarily disable the vibe-d test until vibe.d 0.8.3 has been releases
  # At the moment vibe.d 0.8.2 will be fetched by default - this version doesn't work with dmd-nightly
  - echo > public/content/en/dub/vibe-d.md
  - dub --compiler=${DC} -- --sanitycheck
  # Compile to static binary with ldc
  - if [[ "${DC}" == "ldc2" ]]; then  dub build -c static --compiler=${DC}; fi
  - if [[ "${DC}" == "ldc2" ]]; then docker build -t dlangtour/core . ; fi
  - if [[ "${DC}" == "ldc2" ]]; then docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -ti dlangtour/core --wait-until-pulled --sanitycheck ; fi

after_success:
  - if [[ "${TOUR_DEPLOY}" == "1" && "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - if [[ "${TOUR_DEPLOY}" == "1" && "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]]; then docker push dlangtour/core ; fi
  - bash <(curl -s https://codecov.io/bash)
