port: 8080
public_dir: "public"
listen:
    - 0.0.0.0
google_analytics_id: "%GOOGLE_ANALYTICS_ID%"
exec:
    driver: "docker"
    # For docker driver
    config:
        memory_limit: 256
        maximum_queue_size: 10
        time_limit: 10
        maximum_output_size: 4096
    cache: true
