port: 8080
public_dir: "public"
listen:
    - 0.0.0.0
google_analytics_id: "%GOOGLE_ANALYTICS_ID%"
exec:
    driver: "docker"
    # For docker driver
    config:
        memory_limit: %EXEC_DOCKER_MEMORY_LIMIT%
        maximum_queue_size: %EXEC_DOCKER_MAX_QUEUE_SIZE%
        time_limit: %EXEC_DOCKER_TIME_LIMIT%
        maximum_output_size: %EXEC_DOCKER_MAX_OUTPUT_SIZE%
    cache: true
